#!/bin/bash

realpath() {
    [[ $1 = /* ]] && echo $1 || echo "$PWD/${1#./}"
}

SCRIPT_PATH=`realpath $0`
DOTFILES=`dirname $SCRIPT_PATH`

if [ `uname` == 'Darwin' ]; then
    cd $DOTFILES/setup.d
    ./xcode-cli
    ./brew
    ./mtr
    ./osx-disable-dsstore-network-mounts
fi

# Make sure zgen submodule is cloned
echo "init submodules"
git submodule update --init --recursive

# bin dir
if [ ! -d ~/bin ]; then
    mkdir ~/bin
fi

# vim stuff
if [ ! -d ~/.vim ]; then
    mkdir ~/.vim
fi

if [ ! -d ~/.vim/colors ]; then
    mkdir ~/.vim/colors
    ln -s "$DOTFILES/vim.d/fairyfloss.vim" ~/.vim/colors/fairyfloss.vim
fi

if [ ! -d ~/.vim/backup ]; then
    mkdir ~/.vim/backup
fi

if [ ! -d ~/.vim/bundle ]; then
    mkdir ~/.vim/bundle
fi

if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [ ! -e ~/.vimrc ]; then
    ln -s "$DOTFILES/vimrc" ~/.vimrc
    echo ".vimrc installed successfully"
    vim +PluginInstall +qall
    echo "Plugins installed"
fi

# zsh
if [ ! -e ~/.zshrc ]; then
    ln -s "$DOTFILES/zshrc" ~/.zshrc
    echo ".zshrc installed successfully"
fi

if [ ! -e ~/.zsh.d ]; then
    ln -s "$DOTFILES/zsh.d" ~/.zsh.d
    touch ~/.zsh.d/private.zsh
fi

echo "Remember to add /usr/local/bin/zsh to /etc/shells and run chsh -s /usr/local/bin/zsh"

# git
if [ ! -e ~/.gitignore_global ]; then
    ln -s "$DOTFILES/gitignore_global" ~/.gitignore_global
    echo ".gitignore installed successfully"
fi

$DOTFILES/setup.d/configure-git
echo "Remember to add your git email to global config"

