#!/bin/bash

realpath() {
    [[ $1 = /* ]] && echo $1 || echo "$PWD/${1#./}"
}

SCRIPT_PATH=`realpath $0`
DOTFILES=`dirname $SCRIPT_PATH`


if [ ! -d ~/bin ]; then
    mkdir ~/bin
fi

if [ ! -d ~/.vim ]; then
    mkdir ~/.vim
fi

if [ ! -d ~/.vim/backup ]; then
    mkdir ~/.vim/backup
fi

if [ ! -d ~/.vim/bundle ]; then
    mkdir ~/.vim/bundle
fi

if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [ ! -e ~/.vimrc ]; then
    ln -s "$DOTFILES/vimrc" ~/.vimrc
    echo ".vimrc installed successfully"
    vim +PluginInstall +qall
    echo "Plugins installed"
fi

if [ ! -e ~/.zshrc ]; then
    ln -s "$DOTFILES/zshrc" ~/.zshrc
    echo ".zshrc installed successfully"
fi

if [ ! -e ~/.zsh.d ]; then
    ln -s "$DOTFILES/zsh.d" ~/.zsh.d
    touch ~/.zsh.d/private.zsh
fi

if [ ! -e ~/.gitignore_global ]; then
    ln -s "$DOTFILES/gitignore_global" ~/.gitignore_global
    echo ".gitignore installed successfully"
fi

