# Brewfile

brew 'zsh'
brew 'zsh-completions'
brew 'vim'

brew 'envchain'
brew 'curl'
brew 'wget'
brew 'python'
brew 'git'
brew 'ack'
brew 'the_silver_searcher'
brew 'osxutils'
brew 'moreutils'
brew 'ssh-copy-id'
brew 'tree'
brew 'mobile-shell'
brew 'nmap'
brew 'toilet'
brew 'xz'
brew 'jq'
brew 'jid'
brew 'atool'

brew 'gnupg'
brew 'pinentry-mac'

# php
#tap 'homebrew/homebrew-php'
#brew 'php55-intl'
#brew 'homebrew/php/composer'

# Casks
tap 'caskroom/cask'
cask 'iterm2'
cask 'google-chrome'
cask 'firefox'
cask 'slack'
cask 'visual-studio-code'
cask 'toggl'

cask 'keepassxc'
cask 'divvy'

cask 'pycharm-ce'
cask 'vlc'
cask 'signal'

