#!/bin/bash

brew install git

git config --global user.name "Henk Joubert"
git config --global user.email "jouberthenk@gmail.com"
git config --global color.ui true
git config --global push.default current
git config --global credential.helper store

touch ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

git config --global pager.log 'diff-highlight | less'
git config --global pager.show 'diff-highlight | less'
git config --global pager.diff 'diff-highlight | less'
